### ISSUE TITLE
[FEATURE] Add mobile support

### ISSUE THREAD

**Issue by Beraliv** [haxzie/snipp.in#42]
Hello!

Thank you for your project, looks really great, but unfortunately doesn't work well with mobile:
1. Cannot remove changes
2. Isn't adapted for mobile view (need to use Desktop view)
3. Probably something else (can test more thoroughly later)

If you need help, I can contribute to have these changes 👍

**Comment by haxzie** [comment]
Hey @Beraliv Thanks for opening the issue :raised_hands: 

I'm not primarily focusing on optimizing for mobile since an editor based interface is not very helpful. Plus, Monaco editor has certain issues with how it works with touch interfaces. Having a mobile interface will be helpful once we have the cloud backup available so atleaset we can optimize it for viewing than editing.

**Comment by Beraliv** [comment]
@haxzie I think I will close it for now
